Traceback (most recent call last):
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/nbclient/client.py", line 627, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/nbclient/util.py", line 89, in ensure_async
    result = await obj
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/elijahc/.pyenv/versions/3.7.8/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/nbclient/client.py", line 846, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/nbclient/client.py", line 651, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/elijahc/.pyenv/versions/3.7.8/envs/emu-p37/lib/python3.7/site-packages/nbclient/client.py", line 702, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
# Make sure the files are cached locally
luigi.build(d4_ncs_tasks+[d4_nev],workers=4)
-------------------

